#!/bin/bash
off="$(bluetoothctl show | grep 'Powered: no')"
pid=$(ps -ax | grep -v 'grep' | grep 'bash.*airpods-connect' | cut -d' ' -f3)
if [[ ! -z "$off" ]]; then
    pulseaudio --start
    bluetoothctl power on
    name="$(bluetoothctl paired-devices | cut -d' ' -f2)"
    bluetoothctl connect "$name"
else
    bluetoothctl power off
fi
