#!/bin/bash
# requires dmenu
BOOKDIR="$HOME/Books"
cd "$BOOKDIR"
while ((1)); do
	book=$(ls | dmenu -p 'Book:')
	if [ -d "$book" ]; then
		cd "$book"
	elif [ -f "$book" ]; then
		exec open "$book"
	else
		exit 1
	fi
done
