#!/bin/bash
[ -z "$1" ] && [ ! -f "main.cpp" ] && echo "icpp: No src file" && exit 1
[ ! -z "$1" ] && [ ! -f "$1" ] && echo "icpp: '$1' file does not exist" && exit 1
[ -z "$1" ] && set main.cpp
OUT="/tmp/icpp_tmp_fec951c1"
g++ -std=c++11 $1 -o $OUT || exit 1
# clang++ -std=c++11 $1 -o $OUT || exit 1
$OUT
rm $OUT
