#!/bin/bash
OUT="/tmp/icpp_tmp_0yAqd7rmQPjEMbEMslXM"
[ -z "$1" ] && [ ! -f "main.cpp" ] && echo "icpp: No src file" && exit 1
[ ! -z "$1" ] && [ ! -f "$1" ] && echo "icpp: '$1' file does not exist" && exit 1
[ -z "$1" ] && set main.cpp
g++ -std=c++17 $1 -o $OUT || exit 1
$OUT
rm $OUT
