#!/bin/bash
[ $# -eq 0 ] && echo "Usage: open file1 file2 file3" && exit 0
wrapper=""
while (( $# )); do
	case "$1" in
		-d)
			wrapper="devour"
			;;
		--*)
			;;
		*)
			break
	esac
	shift
done

while (( $# )); do
	if [ ! -e "$1" ]; then
		echo "open: '$(realpath "$1")' does not exist"
		shift
		continue
	fi
	case "$1" in
		*.png|*.pgm|*.jpg)
			prog="sxiv"
			;;
		*.pdf)
			prog="zathura"
			;;
		*.html)
			prog="firefox --private-window"
			;;
		*)
			echo "open: '$(realpath "$1")' unknown file extension"
			shift
			continue
	esac
	$wrapper $prog "$1"
	shift
done
