#!/bin/bash
# followed this guide: https://github.com/dnschneid/crouton/wiki/Using-Cisco-AnyConnect-VPN-with-openconnect
# using packages: openconnect openvpn vpnc net-tools
# the names may differ based on distro, but these should work on Arch
OVX='/usr/sbin/openvpn'
OCX='/usr/sbin/openconnect'
IPX='/bin/ip'
VGRP='UCI'
VURL='https://vpn.uci.edu'
VSCRIPT='/etc/vpnc/vpnc-script'

function PANIC() { echo "$@"; exit 1; }

[ "$EUID" -ne 0 ] && PANIC "ucivpn: root access required."

for FILE in "$OVX" "$OCX" "$IPX" "$VSCRIPT"; do
  [ -f "$FILE" ] || PANIC "ucivpn: $FILE does not exist."
done

ocpid=$(pidof openconnect)
[ ! -z "$ocpid" ] && echo "Killing existing openconnect." && kill -9 $ocpid

$OVX --rmtun --dev tun1
[ -f "/tmp/resolv.conf" ] && cp /tmp/resolv.conf /etc && rm /tmp/resolv.conf

[ $# -ne 0 ] && echo "Closed down VPN." && exit 0

cp /etc/resolv.conf /tmp/resolv.conf.tmp
"$OVX" --mktun --dev tun1 || PANIC "ucivpn: tun1 creation returned with error."
cp /tmp/resolv.conf.tmp /tmp/resolv.conf && rm /tmp/resolv.conf.tmp
ifconfig tun1 up || PANIC "ucivpn: OpenVPN tun1 interface setup returned with error."

"$OCX" -bs "$VSCRIPT" --authgroup="$VGRP" --interface='tun1' "$VURL"
sleep 2
